// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qzznnnsmbkvukymamwjs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6em5ubnNtYmt2dWt5bWFtd2pzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMjQ0MTksImV4cCI6MjA1OTcwMDQxOX0.DQiO4ecM29qYYnAJxlse3-Y3rODEVxjFcQ2ZqzEqjOk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);